#pragma config(Sensor, in1,    leftLine,       sensorReflection)
#pragma config(Sensor, in2,    middleLine,     sensorReflection)
#pragma config(Sensor, in3,    rightLine,      sensorReflection)
#pragma config(Sensor, in4,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl11, skyriseLeft,    sensorDigitalOut)
#pragma config(Sensor, dgtl12, skyriseRIght,   sensorDigitalOut)
#pragma config(Motor,  port1,            ,             tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           flyRight,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           flyLeft,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           driveLeft12,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           driveLeft3,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           driveRight12,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           driveRight3,   tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           vertical,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           horizontal,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,           ,             tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "controller.c"
#include "autonomous.c"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////w////////////////////////////////////////////////////////////

task autonomous() {
	redAuton();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	controller();
}
